CC = g++
IDIR = include
LDIR = libs

compile:
	$(CC) -g -w src/*.cpp vendor/Imgui/*.cpp -o build/program.exe -I$(IDIR) -Ivendor -L$(LDIR) -lmingw32 -lSDL2main -lSDL2_image -lSDL2 -lopengl32 -lglew32 -lImm32
run:
	build/program.exe